<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <base href="/mount/ultralaser_home/Projects/c2_wiki_recovery/out/">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <div class="page">
      <h1>
        <img src="wiki.gif" />
        Empty Catch Clause
      </h1>
      <p>
        You see it all over in Java examples and code: <a href="EmptyCatchClause.html">EmptyCatchClause</a><strong>'s;</strong>
      </p>
      <code>
        try {<br/>
        someObject.something();<br/>
        } catch(Exception e) {<br/>
        // should never happen<br/>
        }<br/>
      </code>
      <p>
        Either code can handle the exception, then the catch clause shouldn't been empty, or the code can not handle the exception, then there should not be a try/catch block at all.
      </p>
      <p>
        Oh, the one designing the interface of the something() method screwed up? Well, try to get it fixed in the method first. If this is not possible, just let the exception pass through (<a href="ThrowDontCatch.html">ThrowDontCatch</a>). If this is not possible (why shouldn't it?), subclass the class of someObject, and provide a wrapper method, which contains the dreaded <a href="EmptyCatchClause.html">EmptyCatchClause</a> <a href="OnceAndOnlyOnce.html">OnceAndOnlyOnce</a>.
      </p>
      <hr/>
      <p>
        Although it would be nice if every exception were valid, that's not always the case.  Sometimes a piece of code throws a checked exception that you <em>know</em> can't occur. Perhaps it's unique to your situation, or you're wrapping a bit of poorly-designed code.  In any case, you don't want to propagate the exception (because then someone <em>else</em> will have to spend cycles dealing with it) and there's no need to handle the exception. In these cases, I like to use an assertion. For example, in a single-threaded app, <a href="InterruptedException.html">InterruptedException</a> can't occur:
      </p>
      <code>
        public void sleep(long delayInMilliseconds) {<br/>
        try {<br/>
        Thread.sleep(delayInMillisecond);<br/>
        }<br/>
        catch (InterruptedException e) {<br/>
        Assert.impossibleException(e);<br/>
        }<br/>
        }<br/>
      </code>
      <p>
        Overall, though, I agree. Empty catch clauses are a definite <a href="CodeSmell.html">CodeSmell</a>. -- <a href="JimLittle.html">JimLittle</a>
      </p>
      <p>
        <em>What about this instead?</em>
      </p>
      <code>
        catch ( InterruptedException iE ) {<br/>
        // somebody interrupted the thread so I could tidy up and stop, maybe I should <br/>
        // have allowed the exception to propagate, or stop and reset the interrupted flag<br/>
        // rather than asserting the impossible.<br/>
        }<br/>
      </code>
      <p>
        -- <a href="AnonymousDonor.html">AnonymousDonor</a>
      </p>
      <hr/>
      <p>
        <em>Contrast it to this:</em>
      </p>
      <code>
        try {<br/>
        someObject.something();<br/>
        } catch(Exception e) {<br/>
        // don't care if it happens<br/>
        }<br/>
      </code>
      <p>
        This still has an empty catch clause, but it has handled the exception. This isn't used for "can't ever happen" scenarios; it's used for "can happen, but it doesn't matter if it does".
      </p>
      <p>
        Note, it's been pointed out to me that expressing this as 
      </p>
      <code>
        try {<br/>
        someObject.something();<br/>
        } catch(Exception unimportant) {}<br/>
      </code>
      <p>
        is more expressive code; it doesn't need the comment.
      </p>
      <hr/>
      <p>
        I would say definitely don't have an empty catch() for the base classes like Throwable or Exception. The someObject.something() call may call many other methods and if one of those throws an Exception, it will be silently caught and it is very frustrating trying to track it down. In these cases I catch an more specific exception (like InterruptedException) or at least add an
        e.printStackTrace() as a temporary measure.
        -- RobNielsen
      </p>
      <hr/>
      <p>
        I say it <strong>is valid</strong> to have an empty catch clause:
        The unchangeable 3rd party package you're using throws an exception for a condition you expect to happen during the normal course of execution of your program, and they didn't think to provide a way to give you a return code instead.
      </p>
      <p>
        For example, I've worked on several applications that would INSERT a record and watch for a "duplicate index entry" error to handle the 2% of the cases where there was a conflict.
        Now one would rather check for that particular error and handle it as a return code, so that alternate business logic can be executed, but I've yet to see a 3rd party database interface that uses exceptions and also gives you that level of control.
        (On one project I wrote such a package - in a layer of C++ wrapper classes over ODBC.)
        So, if you want the main line of your business logic to be rational, you'll want to catch the errant exception and turn it into a special return code.
        The catch block can still end up empty because you might also be using the defensive coding style of setting the return code to "fail" before the try block, and only setting it to "success" at the end of the successful operation. (IE: at the end of the try block.)
        -- <a href="JeffGrigg.html">JeffGrigg</a>
      </p>
      <p>
        <em>Can somebody elaborate on "defensive coding", perhaps with an example?</em>
      </p>
      <p>
        Example:
      </p>
      <code>
        successFlag = FALSE;<br/>
        try {<br/>
        if (doSomethingAndReturnResult() == resultWeLike)<br/>
        successFlag = TRUE;<br/>
        } catch(E<strong>'xceptionTypeWeExpect e) {</strong><br/>
        // 'successFlag' is already FALSE.<br/>
        }<br/>
        return successFlag;<br/>
      </code>
      <hr/>
      <p>
        I think it's the "Can't Ever Happen" comment that represents the smell here. If something "can't ever happen", about five minutes after it gets into production you'll have a long and exhausting debugging session when it does. In such a case, you should throw a runtime exception; after all, one of the fundamental assumptions in the system has just been proven wrong.
      </p>
      <p>
        In the case where there's an empty catch block because you've recognized it can happen, and your way of handling it is to do nothing (as in Jeff's defensive coding technique), it's <em>not</em> a smell. The possibility has been recognized, and the exceptional condition has been dealt with correctly (by ignoring it).
        -- <a href="RobertWatkins.html">RobertWatkins</a>
      </p>
      <p>
        Ooh, ooh, I have one of these.  Consider the case of some session management
        code that periodically expires sessions.
      </p>
      <code>
        try<br/>
        {<br/>
        for (Iterator i = iterator(); i.hasNext();)<br/>
        closeSession( (Session)i.next() );<br/>
        }<br/>
        catch (ConcurrentModificationException cme) {}<br/>
      </code>
      <p>
        One could write some complex exception handling code to try again until all the expired sessions are cleaned up.  But the expiration code will try again very soon. So, the empty catch IS handling the exception by explicitly saying that the right action is to ignore it.  <em>In which case, you should consider this to make that explicit:</em>
      </p>
      <code>
        try<br/>
        {<br/>
        for (Iterator i = iterator(); i.hasNext();)<br/>
        closeSession( (Session)i.next() );<br/>
        }<br/>
        catch (ConcurrentModificationException <strong>ignored</strong>) {}<br/>
      </code>
      <hr/>
      <p>
        See below if you object to this code stopping before the iterator is empty. I'm still a bit puzzled whether a new iterator is created during every iteration, and if so why. If there is some thread issue, isn't there a better way to handle it?
      </p>
      <hr/>
      <p>
        I just love this one - we used to have a programmer working with us who did this so much, we now use his name to describe this "technique". 
      </p>
      <p>
        Another variation (which seems to be caused by programmers inserting print statements everywhere during frantic debugging sessions) is wrapping every line of code with
      </p>
      <code>
        try {<br/>
        ... something ...<br/>
        } catch (Exception e) {<br/>
        e.printStackTrace (System.err);<br/>
        throw e;<br/>
        }<br/>
      </code>
      <p>
        (sometimes nested several levels deep) so whenever you get an exception it's printed out five or ten times over and over. Joy. -- <a href="JamesWilson.html">JamesWilson</a>
      </p>
      <p>
        <em>That's just silly. -- rw</em>
      </p>
      <hr/>
      <p>
        One solution I prefer is to use <a href="RuntimeException.html">RuntimeException</a>. It makes for cleaner code and bugs show up very prominently when you hit an uncaught exception. -- <a href="TimBurns.html">TimBurns</a>
      </p>
      <p>
        <em>I'm disappointed that </em><a href="RuntimeException.html">RuntimeException</a> doesn't have a constructor taking an exception. It would be nice to promote a checked exception to an unchecked one for cases like these. Fortunately, there are a number of implementations of NestedRuntimeExceptions available. -- <a href="MarkAddleman.html">MarkAddleman</a><em></em>
      </p>
      <p>
        No big deal, just write your own Wrapped<a href="RuntimeException.html">RuntimeException</a> that can hold the real exception inside. -- <a href="KyleCordes.html">KyleCordes</a>
      </p>
      <p>
        <em>Sun has recognized this as a flaw - in Merlin (Java 1.4), there will be a new method on the Exception class allowing you to chain them up. I don't know if they'll extend the constructors, but it does make sense -- rw</em>
      </p>
      <p>
        Yes, Sun did add "cause" arguments to some constructors.
      </p>
      <hr/>
      <p>
        <em>Empty catch clauses are a definite </em><a href="CodeSmell.html">CodeSmell</a>.<em></em>
      </p>
      <p>
        I actually vacillate about this. <a href="OnceAndOnlyOnce.html">OnceAndOnlyOnce</a> drives me to want to use Java's checked exceptions as a poor man's extended message syntax.  
      </p>
      <p>
        Without using exceptions, I would write something like
      </p>
      <code>
        Row row = retrieveDbRow(key);<br/>
        if (row == null) {<br/>
        do something<br/>
        }<br/>
      </code>
      <p>
        Assuming that I need to retrieveDbRow and do something if key does not exist more than once, duplicating the if-statement violates <a href="OnceAndOnlyOnce.html">OnceAndOnlyOnce</a>. But, more importantly, it forces me to remember to check for null every time. By making NotFoundException a checked exception, the compiler remembers for me.  
      </p>
      <code>
        try {<br/>
        Row row = retrieveDbRow(key);<br/>
        } catch (NotFoundException e) {<br/>
        do something<br/>
        }<br/>
      </code>
      <p>
        Now, the compiler is working for me and the control flow is pretty clear. It's not as clear as I'd like, but if there is only one statement that throws a NotFoundException and, by convention, that statement is at the start of the try block, the control is pretty clear.
      </p>
      <p>
        The upshot of this style is that there will be cases with <a href="EmptyCatchClause.html">EmptyCatchClause</a>s:
      </p>
      <code>
        try {<br/>
        Row row = retrieveDbRow(key);<br/>
        } catch (NotFoundException e) {<br/>
        }<br/>
      </code>
      <p>
        But, I think this is a more deliberate expression of programmer intent than not having the if-statement.
      </p>
      <p>
        -- <a href="MarkAddleman.html">MarkAddleman</a>
      </p>
      <p>
        <em>I think this is a misunderstanding of the concept of a </em><a href="CodeSmell.html">CodeSmell</a>.  From <a href="CodeSmell.html">CodeSmell</a>s: A perfectly good idiom may be considered a <a href="CodeSmell.html">CodeSmell</a> because it's often misused, or because there's a simpler alternative that works in most cases. Calling something a <a href="CodeSmell.html">CodeSmell</a> is not an attack; it's simply a sign that a closer look is warranted.  -- <a href="AlexChurchill.html">AlexChurchill</a><em></em>
      </p>
      <hr/>
      <p>
        With the pending release of Java 1.4, and the addition of an assert() facility built into the language (as opposed to those hacks which all of us have been using so long), I would say that the correct coding of the initial example is as follows:
      </p>
      <code>
        try {<br/>
        someObject.something();<br/>
        } catch(Exception e) {<br/>
        // should never happen<br/>
        assert(false);<br/>
        }<br/>
      </code>
      <p>
        Here, the assert(false) demonstrates that we know this is an 'impossible' condition (are they ever?), but also tells the runtime to alert us if we were wrong, which just the comment cannot do.
      </p>
      <p>
        <em>Remember that assertions can be switched off and then we would never get this exception. It would be better to log so that program does not crash but the administrator/user/developer can check the logs for errors.</em> -- <a href="VhIndukumar.html">VhIndukumar</a>
      </p>
      <p>
        <em>If the code is not already tied to Java 1.4, it might be excessive to make it so just for the benefit of something that can never happen.</em>
      </p>
      <hr/>
      <p>
        I would be careful about what assumptions you make about the code that threw the exception.  In several of the examples above, the assumption is made that the code fully completed and just threw an exception.  In other examples, it is assumed nothing has happened.  The latter is closer to the intent behind exceptions, but I would take care not to rely upon it. -- <a href="WayneMack.html">WayneMack</a>
      </p>
      <hr/>
      <code>
        try<br/>
        {<br/>
        for (Iterator i = iterator(); i.hasNext();)<br/>
        closeSession( (Session)i.next() );<br/>
        }<br/>
        catch (ConcurrentModificationException cme) {}<br/>
      </code>
      <p>
        Shouldn't this be more something like:
      </p>
      <code>
        for (Iterator i = iterator(); i.hasNext();)<br/>
        {<br/>
        try<br/>
        {<br/>
        closeSession( (Session)i.next() );<br/>
        }<br/>
        catch (ConcurrentModificationException cme) {}<br/>
        }<br/>
      </code>
      <p>
        <em>No, because this is an infinite loop</em>
      </p>
      <p>
        Maybe I misunderstand, but I'm not sure why one would want to stop closing ALL sessions because one happened to throw an expired exception. Of course, if this exception is normal and expected, I don't think I would rely on an exception to control program flow - instead, I would probably do something like this:
      </p>
      <code>
        ...<br/>
        void closeSession( Session ctx )<br/>
        {<br/>
        if ( ! ctx.isExpired() )<br/>
        ctx.close();<br/>
        }<br/>
        ...<br/>
      </code>
      <code>
        for (Iterator i = iterator(); i.hasNext();)<br/>
        {<br/>
        try<br/>
        {<br/>
        closeSession( (Session)i.next() );<br/>
        }<br/>
        catch ( Throwable e )<br/>
        {<br/>
        Logger.printException( e ); // print error and continue<br/>
        }<br/>
        }<br/>
      </code>
      <p>
        This will also execute faster since it does not have to go into the catch block for <em>normal</em> conditions. Also, if there is some unexpected error, it will be logged so that techsupport or developers can see the unusual condition. -- <a href="RobertDiFalco.html">RobertDiFalco</a>
      </p>
      <p>
        I guess I was not being very clear. The ConcurrentModificationException will only happen if someone is trying to add or delete a session while you are going through the list checking for expired sessions. Handling that case seems useless because another aging pass will be made shortly. Also, the iterator is invalid after the exception, so moving the try inside the loop would not work.
      </p>
      <p>
        The first example was snipped too much. Here is the full method:
      </p>
      <code>
        private void ageSessions()<br/>
        {<br/>
        try<br/>
        {<br/>
        for (Iterator i = iterator(); i.hasNext();)<br/>
        {<br/>
        Session session = (Session)i.next();<br/>
        if (!session.isActive())<br/>
        session.close();<br/>
        }<br/>
        }<br/>
        catch (ConcurrentModificationException cme)<br/>
        {<br/>
        The iterator may bail out if someone tries to add or delete<br/>
        a session while we are iterating (fail-fast). When this<br/>
        happens, we don't need to do anything. If we missed any<br/>
        sessions, they will get expired next time around.<br/>
        }<br/>
        }<br/>
      </code>
      <p>
        --<a href="MichaelBanks.html">MichaelBanks</a>
      </p>
      <p>
        Hmmm... in that case, have you considered using an internal iterator and synchronizing on that so that a ConcurrentModificationException is not possible?
      </p>
      <code>
        sessions.enum( new SessionBlock() {<br/>
        public void run( Session each ) {<br/>
        if ( each.isActive() )<br/>
        each.close(); } } );<br/>
      </code>
      <p>
        This makes the transaction across the list atomic and makes the contract for its interface simpler. -- <a href="RobertDiFalco.html">RobertDiFalco</a>
      </p>
      <p>
        I just read the excellent explanation of <a href="InternalIterator.html">InternalIterator</a> and <a href="BlocksInJava.html">BlocksInJava</a>.
        This is a very nice way to avoid the empty catch clause. The only remaining concern is that synchronizing the iterator holds off any opens or closes of new
        sessions for the duration of the iteration. -- <a href="MichaelBanks.html">MichaelBanks</a>
      </p>
      <p>
        <em>I'd think the lock is exactly the problem, at least from one point of view. The first example would be low-priority, pre-emptible cleanup. The locking one might still be low-priority, but it's pre-emptive. Which one you'd choose would depend on whether accumulating garbage has enough consequences that you'd be willing to compromise the main path in order to clean it up. In the case of session management, I'd probably choose the former, but there might be resource leak problem as you scale (cleanup never happens because sessions come in faster than you can expire them), so you might need to move to the second or a hybrid model.</em> --ChrisMellon
      </p>
      <hr/>
      <p>
        What about the problem where closing a stream can throw an <em>IOException</em>.
      </p>
      <code>
        FileInputStream fis;<br/>
        try {<br/>
        fis = new FileInputStream("foo.txt");<br/>
        //  <em>do stuff</em><br/>
        } catch (IOException e) {<br/>
        // warn user<br/>
        } finally {<br/>
        if (fis != null) {<br/>
        try {<br/>
        fis.close();<br/>
        } catch (IOException e) {}  // <a href="EmptyCatchClause.html">EmptyCatchClause</a>?<br/>
        }<br/>
        }<br/>
      </code>
      <p>
        I'm sure the XP theorists really hate that style of code. But, what can you tell a user that makes any sense? At least the common practice in C++ classes is that destructors are written to never throw exceptions.
      </p>
      <p>
        Well, you <em>could</em> create an InputSteamAdapter that hides the try...catch around the #close call. I still wouldn't keep it empty. I would probably write a log entry just in case. -- <a href="RobertDiFalco.html">RobertDiFalco</a>
      </p>
      <p>
        <em>I'd write a log entry because I want to know under what circumstances closing a file can fail...</em>
      </p>
      <hr/>
      <p>
        Well, I prefer to explicitly throw an exception:
      </p>
      <code>
        try {<br/>
        someObject.something();<br/>
        } catch(Exception canNeverHappen) {<br/>
        throw new ImpossibleRuntimeException(canNeverHappen);<br/>
        }<br/>
      </code>
      <p>
        The advantage over the assert style is that the compiler knows an exception will be thrown and won't force me to put in unnecessary return statements etc.
      </p>
      <p>
        -- <a href="NeilSwingler.html">NeilSwingler</a>
      </p>
      <p>
        <em>I like this a lot because I have a strong feeling that, as something() changes, these will start popping up for reasons we couldn't have imagined at first writing.</em> -- <a href="DustinAleksiuk.html">DustinAleksiuk</a>
      </p>
      <p>
        I <a href="HaveThisPattern.html">HaveThisPattern</a> -- <a href="PhilippeDetournay.html">PhilippeDetournay</a>
      </p>
      <hr/>
      <p>
        It is even worse in C++:
      </p>
      <code>
        try {<br/>
        someObject.something();<br/>
        } <br/>
        catch ( ... ) {}<br/>
      </code>
      <p>
        In case something fails, the code will do nothing and continue happily processing. I've seen several times this wrongdoing for avoiding crashes, since this catch even catches access violations (on some platforms, which could reasonably be described as broken for this reason among others). On sane systems, a catch (...) will not interfere with handling of access violations or similar. This is not a C++ problem; it's an MSVC++ problem.
      </p>
      <hr/>
      <p>
        Note that <a href="PeeEmDee.html">PeeEmDee</a> can find this problem.
      </p>
      <hr/>
      <p>
        Whenever its been said "it can never happen", I have suggested putting a System.exit(1) - people aren't so certain then ;) -- <a href="ChanningWalton.html">ChanningWalton</a>
      </p>
      <hr/>
      <p>
        I use something like this for unit testing exception throwing (with <a href="JavaUnit.html">JavaUnit</a>).
      </p>
      <code>
        try {<br/>
        a.mustThrowMyException();<br/>
        fail("My exception should be thrown");<br/>
        } catch (MyException e) {<br/>
        // This SHOULD happen<br/>
        }<br/>
      </code>
      <p>
        I feel like it's a good use of an empty catch clause.
      </p>
      <p>
        <em>Thank you for coming up with the only sane example of an empty Java catch block on this page.  Sorry folks, if you catch one of these other examples you could at least log it.  What?  You say you don't have one... 'nother smell I suppose.</em>
      </p>
      <p>
        Eh, how about:
      </p>
      <code>
        try {<br/>
        a.mustThrowMyException();<br/>
        fail("My exception should be thrown");<br/>
        } catch (MyException expected) {<br/>
        }<br/>
      </code>
      <hr/>
      <p>
        Sorry but I'm going to have to vote for 'Emty catches are sometimes OK'. Take this for example:
      </p>
      <code>
        // (try to) set native L&F<br/>
        try {<br/>
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());<br/>
      </code>
      <code>
        // don't bother handling these, we'll just end up with the<br/>
        // cross-platform look and feel which is fine.<br/>
        } catch (ClassNotFoundException e) {<br/>
        } catch (InstantiationException e) {<br/>
        } catch (IllegalAccessException e) {<br/>
        } catch (UnsupportedLookAndFeelException e) {<br/>
        }<br/>
      </code>
      <p>
        If anything goes wrong, I'm perfectly happy to accept the default look and feel. What would others suggest I do in this situation? Would adding log statements suffice to make the catches non-empty? 
      </p>
      <p>
        Here's another one:
      </p>
      <code>
        try {<br/>
        System.setProperty("java.net.useSystemProxies", "true");<br/>
        } catch (SecurityException e) {<br/>
        // ignore<br/>
        }<br/>
      </code>
      <p>
        I would ideally like to use the system proxy, but if this method fails for whatever reason, I'm happy to continue. So both of these code examples involve trying to set some property or feature, but where failure is acceptable because of sane defaults. <a href="MikeWeller.html">MikeWeller</a>.
      </p>
      <hr/>
      <p>
        And what about this?
      </p>
      <code>
        Socket s = new Socket("somehost",somePort);<br/>
        socket.setSoTimeout(100);<br/>
        try {<br/>
        ObjectInputStream ois = new ObjectInputStream(s.getInputStream()); // it will wait until any data arrive, (or for 100ms, then throw an exception)<br/>
        }<br/>
        catch(SocketTimeoutException e) { /* This is an expected exception, it's a normal working */ }<br/>
        // and i don't wanna wait forever, that's why i'm using timeout.<br/>
      </code>
      <p>
        // and later:
      </p>
      <code>
        Object o;<br/>
        RUN = true;<br/>
        while(RUN) {<br/>
        try {<br/>
        o = readObject(ois);<br/>
        process(o);<br/>
        }<br/>
        catch(SocketTimeoutException e) { /* This is an expected exception, it's a normal working */ }<br/>
        doSomeOtherStuff();<br/>
        }<br/>
      </code>
      <p>
        Let's say, i wanna check RUN in every 100ms, and exit if it's false. (this is a thread, other thread can set RUN=false)
        <a href="MartonSuranyi.html">MartonSuranyi</a>.
      </p>
      <hr/>
      <p>
        <a href="CategoryCodeSmell.html">CategoryCodeSmell</a>. See also <a href="ReplaceEmptyCatchWithTest.html">ReplaceEmptyCatchWithTest</a>.
      </p>
    </div>
  </body>
</html>