<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <base href="/mount/ultralaser_home/Projects/c2_wiki_recovery/out/">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <div class="page">
      <h1>
        <img src="wiki.gif" />
        Exceptions And Constructors
      </h1>
      <p>
        One problem I find when using exceptions in C++ code is when a constructor throws an exception. If I write something like this ...
      </p>
      <code>
        try {<br/>
        Something someThing(params);<br/>
        } catch(Some_Exception e) {<br/>
        // Handle this properly<br/>
        }<br/>
      </code>
      <p>
        ... someThing is no longer in scope by this point, which means that I have to write code like this:
      </p>
      <code>
        try {<br/>
        Something someThing;<br/>
        someThing.Do_Something();<br/>
        } catch(SomeException e) {<br/>
        // Now, who threw the exception?<br/>
        // The constructor or the method call?<br/>
        }<br/>
      </code>
      <p>
        And that I don't like. In this case, I tend to use TwoPhaseConstruction, even though I know it's evil for a host of other reasons.
      </p>
      <p>
        -- <a href="RogerLipscombe.html">RogerLipscombe</a>
      </p>
      <p>
        <em>I can't figure out at all what you are saying here, as someThing isn't in scope in your second example either (perhaps this is the indictment - that even a trivial example requires too much thought). However, it looks to me as though you are trying to do too much in one place. It looks to me as though one of these might meet your needs:</em>
      </p>
      <code>
        try {<br/>
        Something someThing(params);<br/>
        someThing.do () ;<br/>
        } catch(Something_Constructor_Exception e) {<br/>
        // Handle this properly<br/>
        // someThing is not in scope<br/>
        } catch(Something_Do_Exception e ) {<br/>
        // Handle this differently<br/>
        // someThing is not in scope<br/>
        }<br/>
      </code>
      <p>
        <em>or maybe</em>
      </p>
      <code>
        void Do ( Something someThing ) // does not throw SomeException<br/>
        {<br/>
        try {<br/>
        someThing.do () ;<br/>
        } catch ( SomeException e ) {<br/>
        // Handle this properly<br/>
        // someThing is in scope<br/>
        }<br/>
        }<br/>
      </code>
      <code>
        try {<br/>
        Something someThing(params) ;<br/>
        Do( someThing ) ;<br/>
        } catch ( SomeException e ) {<br/>
        // Handle this - it must be an exception in the constructor<br/>
        // someThing not in scope<br/>
        }<br/>
      </code>
      <p>
        <em> -- </em><a href="DanilSuits.html">DanilSuits</a><em></em>
      </p>
      <hr/>
      <p>
        Upon further thought (the therapeutic properties of hot water in action) it seems to me that all code which handles exceptions ought to have the following form:
      </p>
      <code>
        DoSomething ( args )<br/>
        {<br/>
        Context crntContext(args); // Can't throw<br/>
      </code>
      <code>
        try<br/>
        {<br/>
        actuallyDoIt( crntContext ) ;<br/>
        }<br/>
        catch ( Exception1 e )<br/>
        {<br/>
        HandleException1( e, crntContext ) ;<br/>
        }<br/>
        ...<br/>
        catch ( ExceptionN e )<br/>
        {<br/>
        HandleExceptionN( e, crntContext ) ;<br/>
        }<br/>
        }<br/>
      </code>
      <p>
        I'm inclined to think that failure to permit this form is a <a href="CodeSmell.html">CodeSmell</a>. -- <a href="DanilSuits.html">DanilSuits</a>
      </p>
      <hr/>
      <p>
        I think that some of the confusion and frustration can be cleared up by defining when a constructor <em>should</em> throw an exception.  To me, a constructor must throw an exception when instantiation of the object is simply not possible.  This is backed up by the semantics of a constructor exception:  when the constructor throws, it's as if the object never existed in the first place.
      </p>
      <p>
        So the only way to legally write the first example is this:
      </p>
      <code>
        try {<br/>
        Something someThing;<br/>
        try {<br/>
        someThing.Do_Something();<br/>
        } catch(SomeException e) {<br/>
        // someThing decided it was impossible to Do_Something(), so it threw.<br/>
        } <br/>
        } catch(SomeException e) {<br/>
        // someThing doesn't exist, because the constructor found it impossible to instantiate it.<br/>
        } <br/>
      </code>
      <p>
        -- <a href="TimLesher.html">TimLesher</a>
      </p>
      <p>
        (<em>Fixed code so it actually will work; </em><a href="DeleteWhenCooked.html">DeleteWhenCooked</a>.<em>)</em>
      </p>
      <hr/>
      <p>
        <a href="CategoryException.html">CategoryException</a>
      </p>
    </div>
  </body>
</html>