<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <base href="/mount/ultralaser_home/Projects/c2_wiki_recovery/out/">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <div class="page">
      <h1>
        <img src="wiki.gif" />
        Functoids In Cpp Monad Examples
      </h1>
      <p>
        There are facilities in FC++ (see <a href="FunctoidsInCpp.html">FunctoidsInCpp</a>) for programming with Monads in C++. These were designed by the original authors as a way to implement the facilities of the Haskell prelude within C++.
      </p>
      <p>
        There are some brief examples on the web pages at <a href="http://www.cc.gatech.edu/~yannis/fc++/">http://www.cc.gatech.edu/~yannis/fc++/</a>
      </p>
      <p>
        This page discusses some examples of use to see if the ideas discussed on <a href="ResumableException.html">ResumableException</a> can be implemented. -- <a href="JohnFletcher.html">JohnFletcher</a>
      </p>
      <hr/>
      <p>
        <strong>Divide by Zero</strong>
      </p>
      <p>
        FC++ defines a templated variable type called a Maybe<T> which can hold either a value of type T or a failure code which is defined as NOTHING.  Instances can be initialised to a value.
      </p>
      <code>
        Maybe<int> mz;<br/>
        Maybe<int> m4 = just(4);<br/>
        Maybe<int> m0 = just(0);<br/>
      </code>
      <code>
        // Using Maybe to detect a divide by zero.<br/>
        Maybe<int> mdiv(Maybe<int> const &mx, Maybe<int> const &my)<br/>
        {<br/>
        if (mx.is_nothing() ) return mx;<br/>
        else if (my.is_nothing() ) return my;<br/>
        else if (my.value() == 0) return NOTHING;<br/>
        else return just(mx.value() / my.value() );<br/>
        }<br/>
      </code>
      <code>
        mdiv(m4,m4); // 1<br/>
        mdiv(m4,m0); // NOTHING<br/>
      </code>
      <p>
        This can be used to capture a failed state in a similar way to an exception. At the moment there is only one type of exception, but this could be extended. This is the simplest use, it can be extended to work with Monads.
      </p>
      <hr/>
      <p>
        I'm pretty certain that the ability to return a dedicated error-value is insufficient for acting as an exception, much less a resumable one. At best it allows the caller to eventually peek at the result and throw an unResumableException. A <a href="ResumableException.html">ResumableException</a> in the case you describe should allow an exception handler (defined lower in the call stack) to decide policy on what to do after a divide-by-zero event, potentially including the ability to resume the computation with '0' or 'x'.  I know that Haskell has implemented <a href="ExceptionHandling.html">ExceptionHandling</a> with monads, likely even <a href="ResumableException.html">ResumableException</a>s, but it probably involved passing around some big continuations made efficient only by <a href="TailCallOptimization.html">TailCallOptimization</a> and structure-sharing.
      </p>
      <p>
        <em>O.K. I am missing the point, it needs to go back into the routine with a revised action plan. I am familiar with the internals of FC++ and see if anything can be done along the lines of our previous discussions. I am concerned to establish possibilities, rather than worried about efficiency of implementation.</em> -- <a href="JohnFletcher.html">JohnFletcher</a>
      </p>
      <p>
        Perhaps you might better understand the problem if you had a less trivial example. I'll provide one: You are iterating through a large structure, and for each item in that structure you are executing a procedure that is performing some sort of complicated IO task that might fail due to timing issues. On failure, you throw an exception that doesn't really know such details as how far along the programmer was in iterating through the list. We want to make this exception "resumable" by allowing the exception handler to, among other things, choose to "abort" the effort (exiting the iteration loop and continuing on), "retry" that entry (i.e. restart just that entry), or "ignore" and just move on to the next entry. The exception handler will then raise a dialog box for the user of the program, indicating the options to abort, retry, or ignore, and taking an input. Upon selection, the appropriate resumption path is chosen.
      </p>
      <p>
        The basic algorithm:  
      </p>
      <code>
        for(Structure::iterator it = myBigStructure.begin(); myBigStructure.end() != it; ++it)<br/>
        applyFunctor(*it); // might throw exception. Does not know iterator.<br/>
      </code>
      <p>
        Modified for resumption:
      </p>
      <code>
        bool bAbort = false;<br/>
        reset(std::abort&) { bAbort=true; }<br/>
        try {<br/>
        if(!bAbort) {<br/>
        for(Structure::iterator it = myBigStructure.begin(); myBigStructure.end() != it; ++it) {<br/>
        reset(std::retry&) { /* NOP; just continue into 'try' */}<br/>
        reset(std::ignore&) { continue; }<br/>
        try {<br/>
        applyFunctor(*it); // might throw exception. Does not know iterator.<br/>
        }<br/>
        }<br/>
        }<br/>
        }<br/>
      </code>
      <p>
        Some critical points are that the exception handler <em>does not know how</em> to go back into the routine and get it running again (it doesn't know, for example, how many entries had the functor successfully applied), and that the exception handler <em>does not NEED to know how</em> to go back into the routine and get it running again. The exception handler chooses what to do (e.g. 'resume std::retry()'), but does not "revise an action plan" on how to do it. In this particular case, one could wrap an exception handler directly around 'applyFunctor' in the basic algorithm, but doing so would mean that this algorithm would not be reusable: one would need to rewrite the loop for each unique exception handler... for each specific "action plan".
      </p>
      <p>
        If this isn't up your alley, then I apologize for bringing your attention to it.
      </p>
      <p>
        <em>There is no need to apologize for stimulating me to think of new ways of doing things. I will have a look and see if there is any way to do the above example with the technology available to me here.</em> -- <a href="JohnFletcher.html">JohnFletcher</a>
      </p>
      <hr/>
      <p>
        <a href="CategoryCpp.html">CategoryCpp</a> <a href="CategoryFunctionalProgramming.html">CategoryFunctionalProgramming</a>
      </p>
    </div>
  </body>
</html>