<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <base href="/mount/ultralaser_home/Projects/c2_wiki_recovery/out/">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <div class="page">
      <h1>
        <img src="wiki.gif" />
        Object As Success
      </h1>
      <ul>
        <li>
          You are working with methods that either succeed and return some object, or fail.  Many parser methods and rule engine methods are like this.
        </li>
        <li>
          One way to handle this is to define the result of nil as a failure, and any other object as success.  The problem with this is that traditionally nil means "no data" which is not always the same as "method failure".  Sometimes no data is a successful result.
        </li>
        <li>
          Defining false as a failure and any other object as success doesn't feel right, either.
        </li>
        <li>
          Another way to handle this is to define a Result object.  The result object is either a success result object which contains the desired data, or a failure result object that may contain a reason for the failure.  This works, but the extra object is awkward.
        </li>
        <li>
          You want a simpler way.
        </li>
      </ul>
      <p>
        <em>Therefore</em>, define <a href="ObjectAsSuccess.html">ObjectAsSuccess</a>, and create a new Failure class.  Any method result that is not of class Failure is by definition a successful result.
      </p>
      <ul>
        <li>
          Thus, you are adding the object dichotomy success/failure to the existing object dichotomies of true/false and nil/notNil.
        </li>
      </ul>
      <p>
        <em>Example methods</em>
      </p>
      <code>
        Object>ifSuccess: aBlock<br/>
        Object>ifFailure: aBlock<br/>
        Object>ifSuccess: successBlock ifFailure: failureBlock<br/>
        Object>isSuccess<br/>
        Object>isFailure<br/>
        Failure>ifSuccess: aBlock<br/>
        Failure>ifFailure: aBlock<br/>
        Failure>ifSuccess: successBlock ifFailure: failureBlock<br/>
        Failure>isSuccess<br/>
        Failure>isFailure<br/>
      </code>
      <p>
        <em>Example code</em>
      </p>
      <code>
        |result |<br/>
        self rules do: [ :each |<br/>
        result := self fireRule: each with: self.<br/>
        result ifSuccess: [^result].<br/>
        ].<br/>
        ^ Failure onError: 'No matching rule'.<br/>
      </code>
      <hr/>
      <p>
        How does this compare to throwing an exception on failure? One difference is whether you're most likely to just stop processing and bail out (in which case exceptions look cleaner), or to try to continue or repair things on the spot (in which case lots of catch/onExceptionDo: blocks become tedious). Also, I'd be inclined to add a data field to the Failure class so that you can pass back some clue as to why the failure occurred. --<a href="SteveFreeman.html">SteveFreeman</a>
      </p>
      <hr/>
      <p>
        <a href="CategorySuccess.html">CategorySuccess</a>
      </p>
    </div>
  </body>
</html>